query MediaInfoQuery($idIn: [Int]) {
  Page {
    pageInfo {
      hasNextPage
    }
    media(id_in: $idIn) {
      title {
        english,
        native,
        romaji,
        userPreferred
      },
      bannerImage
    }
  }
}