export const MEDIA_CLUB_MEDIA_TAG = 'MEDIA_CLUB_MEDIA';
export const MEDIA_CLUB_USERS_TAG = 'MEDIA_CLUB_USERS';
export const MEDIA_CLUB_FAVORITES_TAG = 'MEDIA_CLUB_FAVORITES';

export const MEDIA_CLUB_TAGS = [
    MEDIA_CLUB_MEDIA_TAG,
    MEDIA_CLUB_USERS_TAG,
    MEDIA_CLUB_FAVORITES_TAG,
];