export const ANILIST_MEDIA_INFO_TAG = 'ANILIST_MEDIA_INFO';
export const ANILIST_USERS_INFO_TAG = 'ANILIST_USERS_INFO';
export const ANILIST_USER_FAVORITES_TAG = 'ANILIST_USER_FAVORITES_TAG';

export const ANILIST_TAGS = [
    ANILIST_MEDIA_INFO_TAG,
    ANILIST_USERS_INFO_TAG,
    ANILIST_USER_FAVORITES_TAG,
];